name:Generate test Feeds
on:[push]
jobs:
  build:
  run-on: ubuntu-latest
  steps:
    -name: chechout Repo
    uses: actions/checkout@v3
    -name: actions/setu-pythom@v4
    with:
      python-version: '3.10'
    -name: Install Dependencies
    run: |
    python -3 pip install --upgrade pip
    pip install pyyaml
    -namee: Run Feed Generate
    run: python feed.py
    - name: Push Repo
    run: push R Repo
    run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add .
    git commit -m "Modified Feed"
    git push
    
